Fixes, compilation symbols, flush & abort * Fixes for Intel compiler. * Checks for alloc/dealloc completion status * Pre-processing symbols * Portable flush and abort subroutines (Toby White) * Cosmetic changes (Toby White, Julian Gale, Alberto Garcia)
Patches applied:

 * agarcia@siesta.arch--2005/siesta-devel--agarcia--1.4--patch-10
   Allow all nodes to write in sys.F

 * agarcia@siesta.arch--2005/siesta-devel--agarcia--1.4--patch-11
   Fix typo in sys.F

 * agarcia@siesta.arch--2005/siesta-devel--agarcia--1.4--patch-12
   Workaround for allocatable issues in Intel compiler

 * agarcia@siesta.arch--2005/siesta-devel--agarcia--1.4--patch-13
   Add checks for alloc/dealloc completion status

 * agarcia@siesta.arch--2005/siesta-devel--agarcia--1.4--patch-14
   Add m_memory to previous patch

 * agarcia@siesta.arch--2005/siesta-devel--agarcia--1.4--patch-15
   New pre-processing symbols for WXML and Scalapack_extra

 * agarcia@siesta.arch--2005/siesta-devel--agarcia--1.4--patch-16
   Add flush to nag.f

 * agarcia@siesta.arch--2005/siesta-devel--agarcia--1.4--patch-17
   Remove debug output in memory.F

 * agarcia@siesta.arch--2005/siesta-devel--agarcia--1.4--patch-18
   Cosmetic issues: transfer, count.

 * agarcia@siesta.arch--2005/siesta-devel--agarcia--1.4--patch-19
   fix format in sys.F -- proc id

 * agarcia@siesta.arch--2005/siesta-devel--agarcia--1.4--patch-20
   remove memorys from memory.F

 * agarcia@siesta.arch--2005/siesta-devel--agarcia--1.4--patch-21
   Portable flush and abort routines (Toby White)

 * agarcia@siesta.arch--2005/siesta-devel--agarcia--1.4--patch-22
   Flush output after every step

 * agarcia@siesta.arch--2005/siesta-devel--agarcia--1.4--patch-23
   frstme and fmt i/o issues in iodm -- chmods

 * agarcia@siesta.arch--2005/siesta-devel--agarcia--1.4--patch-24
   Some fixes by Julian Gale (from Siesta 1.4.54)

 * twhite@siesta.arch--2005/siesta-devel--tw-bugfix--1.4--patch-1
   Rename trasnfer -> atm_transfer

 * twhite@siesta.arch--2005/siesta-devel--tw-bugfix--1.4--patch-2
   Rename count -> alloc_count

 * twhite@siesta.arch--2005/siesta-devel--tw-bugfix--1.4--patch-3
   Include system name in cml output

 * twhite@siesta.arch--2005/siesta-devel--tw-bugfix--1.4--patch-4
   Fix flush & abort issues

 * twhite@siesta.arch--2005/siesta-devel--tw-bugfix--1.4--patch-5
   fix for previous changeset

 * twhite@siesta.arch--2005/siesta-devel--tw-bugfix--1.4--patch-7
   iodm fix

 * twhite@siesta.arch--2005/siesta-devel--tw-bugfix--1.4--patch-8
   Periodic flush of stdout

 * twhite@siesta.arch--2005/siesta-devel--tw-bugfix--1.4--patch-9
   reset dm.formattedinput on second time around.

diff --git a/Src/configure b/Src/configure
--- a/Src/configure
+++ b/Src/configure
@@ -5118,8 +5118,8 @@ fi
 
 
 
-echo "$as_me:$LINENO: checking how to compile a FLUSH subroutine" >&5
-echo $ECHO_N "checking how to compile a FLUSH subroutine... $ECHO_C" >&6
+echo "$as_me:$LINENO: checking how to compile a call to FLUSH" >&5
+echo $ECHO_N "checking how to compile a call to FLUSH... $ECHO_C" >&6
 tw_flush_ok=no
 cat >conftest.$ac_ext <<_ACEOF
 
@@ -5150,7 +5150,7 @@ if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
-  tw_flush_ok=yes; TW_FLUSH=bare;tw_method=default
+  tw_flush_ok=yes; TW_FLUSH=bare;tw_method=default;DEFS="$DEFS FC_HAVE_FLUSH"
 else
   echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
@@ -5190,7 +5190,7 @@ if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
-  tw_flush_ok=yes; TW_FLUSH=INTEL;tw_method="with -Vaxlib"
+  tw_flush_ok=yes; TW_FLUSH=INTEL;tw_method="with -Vaxlib";DEFS="$DEFS FC_HAVE_FLUSH"
 else
   echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
@@ -5233,7 +5233,7 @@ if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
-  tw_flush_ok=yes; TW_FLUSH=NAG;tw_method="with f90_unix_io"
+  tw_flush_ok=yes; TW_FLUSH=NAG;tw_method="with f90_unix_io";DEFS="$DEFS FC_HAVE_FLUSH"
 else
   echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
@@ -5288,6 +5288,178 @@ if test $tw_flush_ok = yes; then
 else
   { { echo "$as_me:$LINENO: error: Cannot compile FLUSH statement" >&5
 echo "$as_me: error: Cannot compile FLUSH statement" >&2;}
+   { (exit 1); exit 1; }; }
+
+fi
+
+
+
+echo "$as_me:$LINENO: checking how to compile a call to ABORT" >&5
+echo $ECHO_N "checking how to compile a call to ABORT... $ECHO_C" >&6
+tw_abort_ok=no
+cat >conftest.$ac_ext <<_ACEOF
+
+      PROGRAM TESTABORT
+      CALL ABORT
+      END PROGRAM TESTABORT
+
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_fc_werror_flag"			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  tw_abort_ok=yes; TW_ABORT=bare;tw_method=default;DEFS="$DEFS FC_HAVE_ABORT"
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+if test $tw_abort_ok = no; then
+   save_LDFLAGS=$LDFLAGS
+   LDFLAGS="$LDFLAGS -Vaxlib"
+   cat >conftest.$ac_ext <<_ACEOF
+
+      PROGRAM TESTABORT
+      CALL ABORT
+      END PROGRAM TESTABORT
+
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_fc_werror_flag"			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  tw_abort_ok=yes; TW_ABORT=INTEL;tw_method="with -Vaxlib";DEFS="$DEFS FC_HAVE_ABORT"
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+   if test $tw_abort_ok = no; then
+      LDFLAGS=$save_LDFLAGS
+   fi
+fi
+if test $tw_abort_ok = no; then
+  cat >conftest.$ac_ext <<_ACEOF
+
+      PROGRAM TESTABORT
+      USE F90_UNIX_PROC, ONLY:ABORT
+      CALL ABORT
+      END PROGRAM TESTABORT
+
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_fc_werror_flag"			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  tw_abort_ok=yes; TW_ABORT=NAG;tw_method="with f90_unix_proc";DEFS="$DEFS FC_HAVE_ABORT"
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+fi
+if test $tw_abort_ok = no; then
+  cat >conftest.$ac_ext <<_ACEOF
+
+      PROGRAM TESTABORT
+      CALL ABORT_
+      END PROGRAM TESTABORT
+
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_fc_werror_flag"			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  tw_abort_ok=yes; TW_ABORT=XLF;tw_method="with underscore"
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: $tw_method" >&5
+echo "${ECHO_T}$tw_method" >&6
+if test $tw_abort_ok = yes; then
+  :
+else
+  { { echo "$as_me:$LINENO: error: Cannot compile call to ABORT " >&5
+echo "$as_me: error: Cannot compile call to ABORT " >&2;}
    { (exit 1); exit 1; }; }
 
 fi
